"""
Django settings for demand_approb_system_main project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Toute la configuration sensible (secrets, mots de passe, clés) vient de
# variables d'environnement, jamais de valeurs écrites en dur dans ce fichier
# versionné — cf. Les Spécifications Techniques §1.2. En local, ces variables
# sont chargées depuis un fichier .env (non versionné, voir .gitignore) ;
# en déploiement IIS, elles viennent des <environmentVariables> de web.config
# (django-environ lit os.environ dans les deux cas : .env ne fait que le
# pré-remplir quand il existe, rien à changer entre les deux environnements).
# Voir .env.example pour la liste des variables et un modèle à copier
# (`cp .env.example .env`) sur un nouveau poste de développement.
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Pas de valeur par défaut ici volontairement : un SECRET_KEY "de secours"
# écrit dans le code fini presque toujours par se retrouver utilisé quelque
# part sans que personne ne le change. Absent de .env => échec explicite au
# démarrage plutôt qu'une clé faible utilisée silencieusement.
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])


# Application definition

INSTALLED_APPS = [
    'unfold',  # doit précéder django.contrib.admin
    'unfold.contrib.filters',
    # `approvals` doit précéder django.contrib.admin : le loader de templates
    # (app_directories) s'arrête à la première app qui fournit un chemin donné,
    # et django.contrib.admin fournit ses propres registration/password_reset_*.html
    # qui écraseraient silencieusement les nôtres si admin passait en premier.
    'approvals',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_json_widget',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sert les fichiers statiques directement depuis le processus applicatif :
    # IIS n'a qu'un seul handler (HttpPlatformHandler) à configurer, pas de
    # chemin virtuel /static/ séparé à mettre en place par la DSI.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demand_approb_system_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'approvals.context_processors.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'demand_approb_system_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQL Server en production (Les Spécifications Techniques §1.1 : "Utilisation
# de Microsoft SQL Server avec le connecteur officiel mssql-django"), SQLite en
# développement local — bascule via la variable d'environnement SQLSERVER_HOST,
# même principe que AUTH_LDAP_SERVER_URI pour l'authentification AD.
# Le mot de passe du compte de service (SQLSERVER_PASSWORD) ne doit jamais être
# écrit en dur, uniquement fourni via l'environnement (cf. §1.2).

SQLSERVER_HOST = env('SQLSERVER_HOST', default='')

if SQLSERVER_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': env('SQLSERVER_NAME', default='demand_approb_system'),
            'HOST': SQLSERVER_HOST,
            'PORT': env('SQLSERVER_PORT', default='1433'),
            'USER': env('SQLSERVER_USER', default=''),
            'PASSWORD': env('SQLSERVER_PASSWORD', default=''),
            'OPTIONS': {
                'driver': env('SQLSERVER_ODBC_DRIVER', default='ODBC Driver 18 for SQL Server'),
                # ODBC Driver 18 vérifie le certificat TLS par défaut ; sur un
                # premier déploiement sans certificat interne encore déployé,
                # SQLSERVER_TRUST_CERT=true permet de démarrer quand même
                # (à désactiver dès que le certificat du serveur est en place).
                'extra_params': (
                    'TrustServerCertificate=yes;'
                    if env.bool('SQLSERVER_TRUST_CERT', default=True)
                    else ''
                ),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-ca'

# Toutes les dates/heures affichées et les échéances (délégations, etc.) sont
# calculées dans le fuseau horaire du siège (retour client).
TIME_ZONE = 'America/Toronto'

USE_I18N = True

USE_TZ = True


# Email (inscription, confirmation de connexion, réinitialisation de mot de
# passe). La configuration SMTP réelle (hôte, identifiants) vit en base via
# EmailSettings, modifiable depuis l'admin sans toucher au code ni redéployer
# (retour client, cf. approvals/email_backend.py) — pas dans settings.py/.env :
# c'est précisément ce que ce mécanisme évite. Pour saisir les identifiants
# Gmail de test, utiliser la page "Configuration email" de l'admin, pas ce
# fichier. Sans configuration active en base, les emails partent sur la
# console (mode dégradé sûr en dev local).
EMAIL_BACKEND = 'approvals.email_backend.DBEmailBackend'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@example.local')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # peuplé par `manage.py collectstatic` au déploiement

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
# Sert aussi les fichiers directement depuis les apps (STATICFILES_FINDERS)
# en secours si `collectstatic` n'a pas été lancé ou est incomplet — évite
# un admin sans CSS. Indépendant de DEBUG (un bug l'y liait auparavant :
# avec DEBUG=False et staticfiles/ absent ou vide, l'admin s'affichait sans
# aucun style). Un vrai déploiement IIS peut forcer la valeur stricte via
# WHITENOISE_USE_FINDERS=False dans web.config, `collectstatic` étant alors
# garanti par le script de déploiement.
WHITENOISE_USE_FINDERS = env.bool('WHITENOISE_USE_FINDERS', default=True)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'approvals:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Logs applicatifs : jamais dans C:\Program Files, toujours dans le profil
# utilisateur du compte de service (Les Spécifications Techniques §1.2 :
# "Les fichiers de logs... doivent pointer vers %APPDATA%\NomApp\Logs").
_LOG_DIR = Path(env('APPDATA', default=str(BASE_DIR))) / 'demand_approb_system_main' / 'Logs'
try:
    _LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    _LOG_DIR = BASE_DIR / 'logs'
    _LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _LOG_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'root': {'handlers': ['console', 'file'], 'level': 'WARNING'},
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'approvals': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}

# Authentification Active Directory (voir "Les Spécifications Techniques" §1.1).
# Backend LDAP en premier (aucun mot de passe local pour un compte AD), puis
# ModelBackend en repli — nécessaire tant qu'AUTH_LDAP_SERVER_URI n'est pas
# configuré (poste de développement local) et pour les comptes de service
# techniques (superuser Django) qui n'existent pas dans l'annuaire.
AUTHENTICATION_BACKENDS = [
    'approvals.auth_backends.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Toutes les valeurs viennent de variables d'environnement : jamais de secret
# (mot de passe du compte de service) en dur dans le code source (cf. Spécifications
# Techniques §1.2). AUTH_LDAP_SERVER_URI vide = backend AD inactif (dev local).
AUTH_LDAP_SERVER_URI = env('AD_LDAP_SERVER_URI', default='')
AUTH_LDAP_BIND_DN = env('AD_LDAP_BIND_DN', default='')
AUTH_LDAP_BIND_PASSWORD = env('AD_LDAP_BIND_PASSWORD', default='')
AUTH_LDAP_USER_SEARCH_BASE = env('AD_LDAP_USER_SEARCH_BASE', default='')
AUTH_LDAP_USER_SEARCH_FILTER = env('AD_LDAP_USER_SEARCH_FILTER', default='(sAMAccountName={username})')
AUTH_LDAP_USERNAME_ATTR = env('AD_LDAP_USERNAME_ATTR', default='sAMAccountName')
AUTH_LDAP_ATTR_MAP = {
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
    'manager': 'manager',
    'department': 'department',
    'site': 'physicalDeliveryOfficeName',
}

UNFOLD = {
    "SITE_TITLE": "Demandes et Approbation",
    "SITE_HEADER": "Demandes et Approbation - Administration",
    "SITE_SYMBOL": "rule",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "LOGIN": {
        "image": None,
    },
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Configuration des demandes",
                "separator": True,
                "items": [
                    {
                        "title": "Types de demandes",
                        "icon": "description",
                        "link": reverse_lazy("admin:approvals_requesttype_changelist"),
                    },
                    {
                        "title": "Règles d'approbation",
                        "icon": "rule",
                        "link": reverse_lazy("admin:approvals_approvalrule_changelist"),
                    },
                    {
                        "title": "Délégations",
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:approvals_delegation_changelist"),
                    },
                ],
            },
            {
                "title": "Suivi",
                "separator": True,
                "items": [
                    {
                        "title": "Demandes",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:approvals_request_changelist"),
                    },
                    {
                        "title": "Journal d'audit",
                        "icon": "history",
                        "link": reverse_lazy("admin:approvals_approvallog_changelist"),
                    },
                    {
                        "title": "Rapports",
                        "icon": "monitoring",
                        "link": reverse_lazy("approvals:reports"),
                    },
                ],
            },
            {
                "title": "Organisation",
                "separator": True,
                "items": [
                    {
                        "title": "Profils utilisateur",
                        "icon": "badge",
                        "link": reverse_lazy("admin:approvals_userprofile_changelist"),
                    },
                    {
                        "title": "Utilisateurs",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groupes",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": "Sécurité",
                "separator": True,
                "items": [
                    {
                        "title": "Configuration email",
                        "icon": "mail",
                        "link": reverse_lazy("admin:approvals_emailsettings_changelist"),
                    },
                ],
            },
        ],
    },
}
