"""
Django settings for demand_approb_system_main project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# En déploiement IIS, ces trois valeurs sont fournies par les variables
# d'environnement du pool d'applications (<environmentVariables> dans
# web.config — voir Les Spécifications Techniques §1.2 : la configuration ne
# doit jamais être écrite en dur dans le code). Les valeurs par défaut
# ci-dessous ne s'appliquent qu'au poste de développement local.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-@f3cx=i6r=i3*llg0mx95+=w@x*a1ps%sz1%%qh*9_3q$f!-be'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'unfold',  # doit précéder django.contrib.admin
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_json_widget',
    'approvals',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sert les fichiers statiques directement depuis le processus applicatif :
    # IIS n'a qu'un seul handler (HttpPlatformHandler) à configurer, pas de
    # chemin virtuel /static/ séparé à mettre en place par la DSI.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'demand_approb_system_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'demand_approb_system_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQL Server en production (Les Spécifications Techniques §1.1 : "Utilisation
# de Microsoft SQL Server avec le connecteur officiel mssql-django"), SQLite en
# développement local — bascule via la variable d'environnement SQLSERVER_HOST,
# même principe que AUTH_LDAP_SERVER_URI pour l'authentification AD.
# Le mot de passe du compte de service (SQLSERVER_PASSWORD) ne doit jamais être
# écrit en dur, uniquement fourni via l'environnement (cf. §1.2).

SQLSERVER_HOST = os.environ.get('SQLSERVER_HOST', '')

if SQLSERVER_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': os.environ.get('SQLSERVER_NAME', 'demand_approb_system'),
            'HOST': SQLSERVER_HOST,
            'PORT': os.environ.get('SQLSERVER_PORT', '1433'),
            'USER': os.environ.get('SQLSERVER_USER', ''),
            'PASSWORD': os.environ.get('SQLSERVER_PASSWORD', ''),
            'OPTIONS': {
                'driver': os.environ.get('SQLSERVER_ODBC_DRIVER', 'ODBC Driver 18 for SQL Server'),
                # ODBC Driver 18 vérifie le certificat TLS par défaut ; sur un
                # premier déploiement sans certificat interne encore déployé,
                # SQLSERVER_TRUST_CERT=true permet de démarrer quand même
                # (à désactiver dès que le certificat du serveur est en place).
                'extra_params': (
                    'TrustServerCertificate=yes;'
                    if os.environ.get('SQLSERVER_TRUST_CERT', 'true').lower() == 'true'
                    else ''
                ),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # peuplé par `manage.py collectstatic` au déploiement

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}
# En dev (DEBUG=True), sert aussi les fichiers directement depuis les apps
# (STATICFILES_FINDERS) pour ne pas avoir à lancer collectstatic à chaque
# changement de CSS/JS local.
WHITENOISE_USE_FINDERS = DEBUG

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'approvals:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Logs applicatifs : jamais dans C:\Program Files, toujours dans le profil
# utilisateur du compte de service (Les Spécifications Techniques §1.2 :
# "Les fichiers de logs... doivent pointer vers %APPDATA%\NomApp\Logs").
_LOG_DIR = Path(os.environ.get('APPDATA', BASE_DIR)) / 'demand_approb_system_main' / 'Logs'
try:
    _LOG_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    _LOG_DIR = BASE_DIR / 'logs'
    _LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'verbose'},
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _LOG_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'formatter': 'verbose',
        },
    },
    'root': {'handlers': ['console', 'file'], 'level': 'WARNING'},
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'approvals': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': False},
    },
}

# Authentification Active Directory (voir "Les Spécifications Techniques" §1.1).
# Backend LDAP en premier (aucun mot de passe local pour un compte AD), puis
# ModelBackend en repli — nécessaire tant qu'AUTH_LDAP_SERVER_URI n'est pas
# configuré (poste de développement local) et pour les comptes de service
# techniques (superuser Django) qui n'existent pas dans l'annuaire.
AUTHENTICATION_BACKENDS = [
    'approvals.auth_backends.ActiveDirectoryBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Toutes les valeurs viennent de variables d'environnement : jamais de secret
# (mot de passe du compte de service) en dur dans le code source (cf. Spécifications
# Techniques §1.2). AUTH_LDAP_SERVER_URI vide = backend AD inactif (dev local).
AUTH_LDAP_SERVER_URI = os.environ.get('AD_LDAP_SERVER_URI', '')
AUTH_LDAP_BIND_DN = os.environ.get('AD_LDAP_BIND_DN', '')
AUTH_LDAP_BIND_PASSWORD = os.environ.get('AD_LDAP_BIND_PASSWORD', '')
AUTH_LDAP_USER_SEARCH_BASE = os.environ.get('AD_LDAP_USER_SEARCH_BASE', '')
AUTH_LDAP_USER_SEARCH_FILTER = os.environ.get('AD_LDAP_USER_SEARCH_FILTER', '(sAMAccountName={username})')
AUTH_LDAP_USERNAME_ATTR = os.environ.get('AD_LDAP_USERNAME_ATTR', 'sAMAccountName')
AUTH_LDAP_ATTR_MAP = {
    'first_name': 'givenName',
    'last_name': 'sn',
    'email': 'mail',
    'manager': 'manager',
    'department': 'department',
    'site': 'physicalDeliveryOfficeName',
}

UNFOLD = {
    "SITE_TITLE": "Administration — Demandes & Approbation",
    "SITE_HEADER": "Demandes & Approbation",
    "SITE_SYMBOL": "rule",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "LOGIN": {
        "image": None,
    },
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Configuration des demandes",
                "separator": True,
                "items": [
                    {
                        "title": "Types de demandes",
                        "icon": "description",
                        "link": reverse_lazy("admin:approvals_requesttype_changelist"),
                    },
                    {
                        "title": "Règles d'approbation",
                        "icon": "rule",
                        "link": reverse_lazy("admin:approvals_approvalrule_changelist"),
                    },
                    {
                        "title": "Délégations",
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:approvals_delegation_changelist"),
                    },
                ],
            },
            {
                "title": "Suivi",
                "separator": True,
                "items": [
                    {
                        "title": "Demandes",
                        "icon": "assignment",
                        "link": reverse_lazy("admin:approvals_request_changelist"),
                    },
                    {
                        "title": "Journal d'audit",
                        "icon": "history",
                        "link": reverse_lazy("admin:approvals_approvallog_changelist"),
                    },
                    {
                        "title": "Rapports",
                        "icon": "monitoring",
                        "link": reverse_lazy("approvals:reports"),
                    },
                ],
            },
            {
                "title": "Organisation",
                "separator": True,
                "items": [
                    {
                        "title": "Profils utilisateur",
                        "icon": "badge",
                        "link": reverse_lazy("admin:approvals_userprofile_changelist"),
                    },
                    {
                        "title": "Utilisateurs",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groupes",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
