# Generated by Django 6.0.7 on 2026-07-20 14:03

import approvals.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('form_schema', models.JSONField(default=dict, validators=[approvals.validators.validate_form_schema])),
                ('schema_version', models.IntegerField(default=1)),
                ('resume_on_resubmit', models.BooleanField(default=False, help_text='Si activé, une demande retournée puis resoumise reprend au niveau bloqué au lieu de redémarrer au niveau 1.')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marque les demandes de ce type comme sensibles (ex: congé médical).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Limite la délégation à certains types de demande. Ex: {"request_type_ids": [1, 5]}. Vide = délégation totale.', null=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Refusée'), ('RETURNED', 'Retournée')], default='DRAFT', max_length=10)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('snapshot_metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='approvals.requesttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('SUBMIT', 'Soumission'), ('APPROVE', 'Approbation'), ('REJECT', 'Refus'), ('RETURN', 'Retour'), ('RULE_CHANGE', 'Modification de règle'), ('DELEGATION_TRIGGERED', 'Délégation déclenchée')], max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=10, null=True)),
                ('new_status', models.CharField(blank=True, max_length=10, null=True)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approvals.request')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='1 = premier niveau (Manager), 2 = Directeur, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('criteria', models.JSONField(blank=True, default=dict, validators=[approvals.validators.validate_criteria])),
                ('approvers_config', models.JSONField(default=dict, validators=[approvals.validators.validate_approvers_config])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='approvals.requesttype')),
            ],
            options={
                'ordering': ['request_type', 'level'],
            },
        ),
    ]
