# Generated by Django 6.0.7 on 2026-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvallog',
            name='action_type',
            field=models.CharField(choices=[('SUBMIT', 'Soumission'), ('APPROVE', 'Approbation'), ('REJECT', 'Refus'), ('RETURN', 'Retour'), ('RULE_CHANGE', 'Modification de règle'), ('DELEGATION_TRIGGERED', 'Délégation déclenchée'), ('FORCE_ADVANCE', 'Passage forcé (intervention admin)'), ('REASSIGN', 'Réassignation (intervention admin)')], max_length=25),
        ),
    ]
