# Generated by Django 6.0.7 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvallog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_ad_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department_id',
            field=models.IntegerField(blank=True, help_text="ID numérique utilisé par les critères de règles (ApprovalRule.criteria.department_ids). À renseigner manuellement par un admin fonctionnel : l'annuaire AD ne fournit qu'un nom de département (department_name), pas d'identifiant numérique stable.", null=True),
        ),
    ]
