# Generated by Django 6.0.7 on 2026-07-21 12:54

import approvals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_userprofile_department_name_userprofile_last_ad_sync_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: "Gmail (test)", "Exchange (production)".', max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Une seule configuration active à la fois (la dernière activée gagne).')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('_password_encrypted', models.TextField(blank=True, db_column='password_encrypted')),
                ('use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(help_text='Adresse affichée comme expéditeur.', max_length=254)),
                ('require_login_confirmation', models.BooleanField(default=True, help_text="Si activé, la connexion nécessite de cliquer un lien reçu par email avant d'être effective (double authentification par email).")),
            ],
            options={
                'verbose_name': 'Configuration email',
                'verbose_name_plural': 'Configuration email',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('EMAIL_CONFIRM', "Confirmation d'inscription"), ('LOGIN_CONFIRM', 'Confirmation de connexion')], max_length=20)),
                ('token', models.CharField(default=approvals.models._generate_token, max_length=64, unique=True)),
                ('backend_path', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
