# Generated by Django 6.0.7 on 2026-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_emailsettings_userprofile_email_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='default_currency',
            field=models.CharField(blank=True, default='', help_text='Devise affichée pour les montants de ce type de demande (ex: EUR, USD, CAD). Laisser vide si ce type ne comporte pas de montant.', max_length=10),
        ),
    ]
