# Generated by Django 6.0.7 on 2026-07-21 17:13

import approvals.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_requesttype_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG ou PNG, 2 Mo maximum.', null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), approvals.models.validate_profile_photo_size]),
        ),
    ]
