# Generated by Django 6.0.7 on 2026-07-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0008_requestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='site_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Utilisé par les critères de règles (ApprovalRule.criteria.department_ids). À renseigner manuellement par un admin fonctionnel : l'annuaire AD ne fournit qu'un nom de département (department_name), pas d'identifiant stable.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='approvals.department'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='approvals.site'),
        ),
    ]
