# Generated by Django 6.0.7 on 2026-07-28 19:55

import approvals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_department_site_remove_userprofile_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[approvals.validators.validate_entity_name]),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='label',
            field=models.CharField(help_text='Ex: "Gmail (test)", "Exchange (production)".', max_length=100, validators=[approvals.validators.validate_entity_name]),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[approvals.validators.validate_entity_name]),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[approvals.validators.validate_entity_name]),
        ),
    ]
