# Generated by Django 6.0.7 on 2026-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_alter_department_name_alter_emailsettings_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
