# Generated by Django 6.0.7 on 2026-07-30 17:15

import approvals.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0011_userprofile_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[approvals.validators.validate_entity_name])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Rôle métier librement défini (ex: "Comptable") — purement descriptif, distinct du rôle système affiché juste à côté (Super admin/Admin fonctionnel/Manager/Demandeur, calculé à partir des permissions réelles).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='approvals.role'),
        ),
    ]
