# Generated by Django 6.0.7 on 2026-08-04 13:09

from django.db import migrations, models


def backfill_references(apps, schema_editor):
    """Les demandes déjà existantes n'ont pas de référence : on leur en
    attribue une par ordre chronologique (création), type par type, pour
    que la contrainte unique posée juste après ne plante pas sur des
    valeurs vides en double."""
    RequestType = apps.get_model("approvals", "RequestType")
    Request = apps.get_model("approvals", "Request")

    for request_type in RequestType.objects.all():
        number = 0
        requests = Request.objects.filter(request_type=request_type).order_by("created_at")
        for req in requests:
            number += 1
            req.reference = f"{request_type.code}-{number:06d}"
            req.save(update_fields=["reference"])
        if number:
            request_type.last_reference_number = number
            request_type.save(update_fields=["last_reference_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0012_role_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='last_reference_number',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Compteur interne utilisé pour générer la référence (ex: EXPENSE-000001) de chaque nouvelle demande de ce type — ne pas modifier manuellement.'),
        ),
        migrations.AddField(
            model_name='request',
            name='reference',
            field=models.CharField(blank=True, default='', editable=False, help_text="Code séquentiel lisible (ex: EXPENSE-000042), attribué automatiquement à la création — sert à distinguer deux demandes du même type dans les listes, l'UUID n'étant pas lisible.", max_length=30),
        ),
        migrations.RunPython(backfill_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='request',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text="Code séquentiel lisible (ex: EXPENSE-000042), attribué automatiquement à la création — sert à distinguer deux demandes du même type dans les listes, l'UUID n'étant pas lisible.", max_length=30, unique=True),
        ),
    ]
