# Generated by Django 6.0.7 on 2026-08-04 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0013_request_reference_requesttype_last_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='reference_form_pdf',
            field=models.FileField(blank=True, help_text="Document PDF expliquant ce qui est attendu pour ce type de demande (ex: le formulaire papier existant). Affiché au demandeur à côté du formulaire en ligne, et à l'approbateur lors de la révision — à titre de référence, les champs ci-dessus restent la source des données enregistrées.", null=True, upload_to='request_type_forms/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
