# Generated by Django 6.0.7 on 2026-08-04 18:57

import approvals.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0014_requesttype_reference_form_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(blank=True, help_text="Affiché en haut du PDF, sous les logos (ex: adresse de l'entreprise, numéro de document, date de révision).")),
                ('footer_text', models.TextField(blank=True, help_text='Affiché en bas de chaque page du PDF (ex: mentions légales).')),
                ('request_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='approvals.requesttype')),
            ],
            options={
                'verbose_name': 'Habillage de document',
                'verbose_name_plural': 'Habillages de document',
            },
        ),
        migrations.CreateModel(
            name='BrandingLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='branding_logos/%Y/%m/', validators=[approvals.models._validate_logo_extension])),
                ('order', models.PositiveIntegerField(default=0)),
                ('branding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='approvals.documentbranding')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
