# Generated by Django 6.0.7 on 2026-08-04 19:54

import approvals.models
import approvals.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0015_documentbranding_brandinglogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[approvals.validators.validate_entity_name])),
                ('regular_ttf', models.FileField(upload_to='custom_fonts/', validators=[approvals.models._validate_ttf_extension])),
                ('bold_ttf', models.FileField(blank=True, null=True, upload_to='custom_fonts/', validators=[approvals.models._validate_ttf_extension])),
                ('italic_ttf', models.FileField(blank=True, null=True, upload_to='custom_fonts/', validators=[approvals.models._validate_ttf_extension])),
                ('bold_italic_ttf', models.FileField(blank=True, null=True, upload_to='custom_fonts/', validators=[approvals.models._validate_ttf_extension])),
            ],
            options={
                'verbose_name': 'Police personnalisée',
                'verbose_name_plural': 'Polices personnalisées',
            },
        ),
        migrations.AlterField(
            model_name='documentbranding',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Affiché en bas de chaque page du PDF (ex: mentions légales) — mise en forme simple possible (gras/italique/souligné/alignement).'),
        ),
        migrations.AlterField(
            model_name='documentbranding',
            name='header_text',
            field=models.TextField(blank=True, help_text="Affiché en haut du PDF, sous les logos (ex: adresse de l'entreprise, numéro de document, date de révision) — mise en forme simple possible (gras/italique/souligné/alignement)."),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_json', models.JSONField(blank=True, default=dict, help_text="Représentation Fabric.js de la mise en page — ne pas modifier manuellement, généré par l'éditeur visuel.")),
                ('request_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_template', to='approvals.requesttype')),
            ],
            options={
                'verbose_name': 'Mise en page personnalisée',
                'verbose_name_plural': 'Mises en page personnalisées',
            },
        ),
    ]
