# Generated by Django 6.0.7 on 2026-08-05 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0016_customfont_alter_documentbranding_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbranding',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Couleur des titres de section et des champs mis en évidence (format #RRGGBB). Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
    ]
