# Generated by Django 6.0.7 on 2026-08-05 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0017_documentbranding_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbranding',
            name='body_font',
            field=models.CharField(blank=True, help_text="Police du corps du document — Helvetica, Times, Courier, ou le nom exact d'une police personnalisée (voir Polices personnalisées). Laisser vide pour Helvetica.", max_length=100),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='body_font_size',
            field=models.PositiveIntegerField(default=11, help_text='Taille de police (points) des valeurs des champs — titres, labels et titres de section restent proportionnels à cette taille.', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='line_spacing',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('spacious', 'Aéré')], default='normal', help_text='Espacement entre les lignes et les paragraphes du PDF.', max_length=10),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='underline_values',
            field=models.BooleanField(default=False, help_text='Affiche un trait fin sous chaque valeur courte, comme un formulaire papier (ex: "Nom : ______________").'),
        ),
    ]
