# Generated by Django 6.0.7 on 2026-08-05 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0018_documentbranding_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbranding',
            name='approved_color',
            field=models.CharField(blank=True, help_text='Couleur du statut "Approuvée" dans le PDF. Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='draft_color',
            field=models.CharField(blank=True, help_text='Couleur du statut "Brouillon" dans le PDF. Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='footer_color',
            field=models.CharField(blank=True, help_text='Couleur du pied de page (format #RRGGBB). Laisser vide pour un gris neutre.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='footer_font_size',
            field=models.PositiveIntegerField(default=8, help_text='Taille de police (points) du pied de page.', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='pending_color',
            field=models.CharField(blank=True, help_text='Couleur du statut "En attente" dans le PDF. Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='rejected_color',
            field=models.CharField(blank=True, help_text='Couleur du statut "Refusée" dans le PDF. Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
        migrations.AddField(
            model_name='documentbranding',
            name='returned_color',
            field=models.CharField(blank=True, help_text='Couleur du statut "Retournée" dans le PDF. Laisser vide pour la couleur par défaut.', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Format attendu : #RRGGBB (ex: #1F3A5F).')]),
        ),
    ]
