# Generated by Django 6.0.7 on 2026-08-05 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0019_documentbranding_approved_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentbranding',
            name='footer_image',
            field=models.ImageField(blank=True, help_text='Image ou icône affichée en bas à gauche de chaque page (ex: sceau, certification) — optionnel.', null=True, upload_to='branding_footer/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
