# Generated by Django 6.0.7 on 2026-08-05 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0020_documentbranding_footer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
