# Generated by Django 6.0.7 on 2026-08-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0021_userprofile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='context_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.department'),
        ),
        migrations.AddField(
            model_name='request',
            name='context_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.site'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='requires_context_selection',
            field=models.BooleanField(default=False, help_text="Si activé, le demandeur doit choisir le département (et éventuellement le site) concerné par SA demande — utilisé pour router l'approbation, à la place du département/site de son propre profil. À activer quand l'approbateur pertinent dépend du sujet de la demande plutôt que de qui la fait (ex: achat pour un autre département)."),
        ),
    ]
